name: flutter_tally_erp
description: "A complete Flutter package to connect with Tally ERP 9 and Tally Prime via official XML over HTTP API. Generate a mobile ERP interface instantly."
version: 1.0.2
homepage: https://github.com/febin52/tally_ui_helper
repository: https://github.com/febin52/tally_ui_helper
issue_tracker: https://github.com/febin52/tally_ui_helper/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  xml: ^6.6.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
